#!/usr/bin/env node
'use strict';
/**
 * FROZEN PRINCIPAL ACCEPTANCE ORACLE — Pharmacy Act v1 common contract
 * WO-NEXUS-FARMACIA-F4.4A / issue #488 (parent train #487, T1)
 * =====================================================================
 *
 * Authority basis (frozen before the implementation context received write
 * authority; this oracle may disagree with the implementation):
 *   - Issue #488 (WO-NEXUS-FARMACIA-F4.4A) — binding contract authority for
 *     the surface `HubTools.farmaciaActContract.createAct({ ... })` in
 *     `modules/farmacia_act_contract.js`.
 *   - `docs/architecture/PROMUEVE_ARCHITECTURE_DECISION_FREEZE_20260924.md`
 *     §6 (contratos de escritura: envelope conceptual mínimo, acto completo
 *     independiente de la fila de transporte, `commit(event)` rechazado) and
 *     §7 (persistencia/adapters: Excel es proyección, no dominio).
 *   - `docs/ops/PROMUEVE_FOUNDATION_TRAIN_PLAN_20260924.md` F4.4.
 *   - CODING_STANDARDS §7 (verification must be able to disagree), §8 (fail
 *     explicitly; UNKNOWN is not SUCCESS), §12 (preserve explicit clinical
 *     meaning; never turn absence into a default), §13 (no hidden
 *     normalization), §14 (no clinical apply/inference at the common layer).
 *   - Clinical boundaries (AGENTS.md): solicitado ≠ validado; previo ≠ nuevo;
 *     followup ≠ validación; ningún default terapéutico; la ausencia
 *     permanece ausencia. The common layer must not introduce clinical
 *     meaning: it neither interprets payload nor completes the act from
 *     medication name, catalog, CIMA, history, DOM or storage.
 *   - Structural precedent `tools/reuma_act_contract_check.mjs` (#462) —
 *     pattern only, NOT Reuma semantics.
 *
 * The module under test (`modules/farmacia_act_contract.js`) is loaded
 * UNMODIFIED inside a Node `vm` sandbox with the browser globals the
 * repository modules expect (same convention as the Reuma oracle), with ONLY
 * `modules/hubTools.js` preloaded as the `window.HubTools` namespace host.
 * Export v2 core is deliberately NOT loaded: the contract must be
 * independent of it (transport-independence oracle negatives, family E).
 *
 * FROZEN DECISION LOG (each place #488 was silent, the most fail-closed
 * interpretation was chosen; derivable from #488 + §8/§12/§13):
 *
 *   D1 `kind` matching is EXACT-TOKEN: only the strings 'pharmacy_validation',
 *      'pharmacy_first_visit', 'pharmacy_followup' (vocabulary characterized
 *      by the published Export v2 core; reuse creates NO dependency on it).
 *      No trimming, no case folding, no dash/underscore normalization, no
 *      aliases ('validation', 'VALIDACION', 'pharmacy-validation',
 *      'pharmacy_validation ' all fail). The three kinds are independent
 *      operations: no implicit chaining is expressible at this layer.
 *
 *   D2 Non-empty identity strings (`actId`, `siteId`, `patientRef`,
 *      `authorRef`, `attributionAssurance`) must be values of type `string`
 *      with at least one non-whitespace character. Empty, whitespace-only,
 *      missing and non-string values fail closed. They are echoed verbatim
 *      (never trimmed, never inferred, never generated).
 *      `attributionAssurance` is NOT enumerated by T1: #488 forbids
 *      inventing an unpublished internal taxonomy, so any explicit non-empty
 *      string is accepted and the vocabulary belongs to the caller/domain.
 *
 *   D3 `revision` must be an integer >= 1 (Number.isInteger; 0, negatives,
 *      1.5, '1', NaN, Infinity, booleans, objects fail closed).
 *
 *   D4 `occurredAt` and `authoredAt` must be explicit ISO-8601 date-time
 *      STRINGS (calendar date + 'T' + time, optional fraction, optional
 *      Z/±HH:MM offset) that also parse as real calendar dates
 *      (Date.parse). Date-only strings, space-separated datetimes, locale
 *      formats ('30/09/2026'), 'now', epoch numbers, Date objects and
 *      impossible dates ('2026-13-01T...', '2026-02-30T...') fail closed.
 *      The module NEVER calls Date.now()/new Date() to complete the act
 *      (verified behaviorally with an instrumented Date, family E): no
 *      metadata is autogenerated.
 *
 *   D5 `payload` and `provenance` must be explicit PLAIN objects (prototype
 *      Object.prototype or null; non-null, non-array). They are opaque to
 *      this layer: the contract imposes NO schema on their content and
 *      invents no clinical meaning. Their internal structure is restricted
 *      to lossless supported types — plain objects, arrays, string, finite
 *      number, boolean, null, present-with-undefined. Functions, symbols,
 *      bigints, boxed/exotic objects (Date, Map, Set, RegExp, class
 *      instances), non-finite numbers and reference cycles fail closed with
 *      a typed structured error; nothing is normalized silently.
 *
 *   D6 `amendment` is OPTIONAL: `undefined` means absent and the ok result
 *      carries NO 'amendment' key at all (no null placeholder, no default).
 *      If the key is present with any other value, it must be a plain object
 *      with EXACTLY the keys { previousRevision, reason } where
 *      `previousRevision` is an integer >= 1 and strictly < `revision`, and
 *      `reason` is a non-empty string. Extra keys, missing keys and any
 *      violation fail closed (the §6.2 freeze defines amendment as exactly
 *      { previousRevision, reason }).
 *
 *   D7 Ok-result shape: the ok result carries EXACTLY the keys { ok,
 *      contractVersion, actId, revision, kind, siteId, patientRef,
 *      occurredAt, authoredAt, authorRef, attributionAssurance, provenance,
 *      payload } plus `amendment` ONLY when explicitly provided. No
 *      additional key (createdAt, generatedAt, id, status, actor, row...,
 *      anything) may appear: the act is completed exclusively from the
 *      explicit input + the contract-owned contractVersion. Two creations
 *      from identical explicit input must be deep-identical (no hidden
 *      clock, counter or randomness).
 *
 *   D8 Failure shape: invalid input NEVER throws and NEVER fabricates a
 *      partial act. It returns { ok: false, error: { code, message } } with
 *      a non-empty string `code` and a string `message`, and EXACTLY the
 *      keys { ok, error } (no envelope field is exposed on a failure). The
 *      exact code strings are implementation-chosen (#488 is silent) but
 *      must be typed and structured.
 *
 *   D9 Preservation is strict: a key explicitly present with value
 *      `undefined` must REMAIN present-with-undefined in the copied
 *      payload/provenance (distinguishable from a genuinely missing key via
 *      `in`/Object.keys); '', 0, false, null and non-empty strings are
 *      preserved verbatim with their types; nested objects/arrays are
 *      deep-copied with no key dropped and no sentinel collapsed (§12).
 *      Shared-but-acyclic references inside one structure are legal input
 *      (copied, not treated as cycles).
 *
 *   D10 Immutability at the level the ticket guarantees: the act (including
 *      payload, provenance and amendment) must be PROVABLY DETACHED from
 *      the inputs — deep copy, new references for nested objects/arrays —
 *      so no caller reference can mutate the result and the result cannot
 *      mutate the inputs. The oracle proves detachment bidirectionally with
 *      mutation probes (same interpretation frozen as D8 of the Reuma
 *      precedent #462). Creating the act must not mutate
 *      input/payload/provenance/amendment originals.
 *
 *   D11 Transport ignorance is checked BOTH statically (the module source
 *      must not reference FarmaciaExportV2Core, ROW_COLUMNS,
 *      ROW_SCHEMA_VERSION, row_id/row_index/row_count/row_role,
 *      bridge_status, TSV, clipboard, Excel/worksheet, SharePoint, SQL,
 *      commit(, Date.now, Math.random, import/require, document/localStorage)
 *      and behaviorally (loads with only hubTools.js; attaches ONLY
 *      HubTools.farmaciaActContract; HubTools.export stays empty). Forbidden
 *      occurrences fail even inside comments: the contract must not know the
 *      transport at all.
 *
 * Exit codes: 0 = all cases PASS, 1 = at least one case FAIL (fail-closed;
 * with the module under test absent, every case FAILs).
 * Usage: node tools/farmacia_act_contract_check.mjs   (from repo root)
 */

import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const HUB_TOOLS_MODULE = 'modules/hubTools.js';
const CONTRACT_MODULE = 'modules/farmacia_act_contract.js';

const CONTRACT_VERSION = 'pharmacy-act/v1';
const KINDS = ['pharmacy_validation', 'pharmacy_first_visit', 'pharmacy_followup'];
const BASE_ENVELOPE_KEYS = ['actId', 'attributionAssurance', 'authoredAt', 'authorRef', 'contractVersion', 'kind', 'occurredAt', 'ok', 'patientRef', 'payload', 'provenance', 'revision', 'siteId'].sort();
const WITH_AMENDMENT_KEYS = [...BASE_ENVELOPE_KEYS, 'amendment'].sort();

// ---------------------------------------------------------------------------
// Recording
// ---------------------------------------------------------------------------

const results = [];
const record = (name, pass, detail) => {
    results.push({ name, pass });
    console.log(`  [${pass ? 'OK ' : 'FAIL'}] ${name}${pass ? '' : ` -> ${detail}`}`);
};
const plantedSink = [];
const plantedRecord = (name, pass, detail) => {
    plantedSink.push({ name, pass });
    console.log(`      (planted) [${pass ? 'OK ' : 'FAIL'}] ${name}${pass ? '' : ` -> ${detail}`}`);
};
// Each family runs exactly one planted lie; the sink is reset per family so
// the "detected as false" assertion is family-local.
const plantedDetectedAsFalse = () => plantedSink.length === 1 && plantedSink[0].pass === false;
const plantedSummary = () => `planted pass=${plantedSink.length === 1 ? plantedSink[0].pass : 'n/a'}`;

// ---------------------------------------------------------------------------
// Sandbox (browser-scoped vm, only hubTools.js preloaded as namespace host)
// ---------------------------------------------------------------------------

function createCapturingConsole(sink) {
    const relay = (level) => (...args) => {
        sink.logs.push({ level, message: args.map((a) => (typeof a === 'string' ? a : String(a))).join(' ') });
    };
    return { log: relay('log'), warn: relay('warn'), error: relay('error'), info: relay('log') };
}

function createStorageShim() {
    const store = new Map();
    return {
        getItem: (key) => (store.has(String(key)) ? store.get(String(key)) : null),
        setItem: (key, value) => { store.set(String(key), String(value)); },
        removeItem: (key) => { store.delete(String(key)); },
        clear: () => { store.clear(); },
    };
}

function createContractSandbox(options = {}) {
    const sink = { logs: [] };
    const clock = { nowCalls: 0, ctorCalls: 0 };
    const sandbox = {
        console: createCapturingConsole(sink),
        setTimeout,
        clearTimeout,
        navigator: { userAgent: 'promueve-act-contract-oracle/1' },
    };
    sandbox.window = sandbox;
    sandbox.self = sandbox;
    sandbox.globalThis = sandbox;
    sandbox.sessionStorage = createStorageShim();
    sandbox.localStorage = createStorageShim();
    sandbox.CustomEvent = class CustomEvent {
        constructor(type, options2) {
            this.type = type;
            this.detail = options2 ? options2.detail : undefined;
        }
    };
    sandbox.document = {
        dispatchEvent: () => true,
        addEventListener: () => {},
        removeEventListener: () => {},
        getElementById: () => null,
        createElement: () => ({ style: {}, setAttribute() {}, appendChild() {}, removeChild() {}, remove() {} }),
    };
    sandbox.dispatchEvent = () => true;
    sandbox.addEventListener = () => {};
    sandbox.removeEventListener = () => {};
    sandbox.requestAnimationFrame = (fn) => setTimeout(fn, 0);
    if (options.instrumentClock) {
        class InstrumentedDate extends Date {
            constructor(...args) {
                if (args.length === 0) clock.ctorCalls += 1;
                super(...args);
            }
            static now() {
                clock.nowCalls += 1;
                return 0;
            }
        }
        sandbox.Date = InstrumentedDate;
    }
    vm.createContext(sandbox);
    return { sandbox, sink, clock };
}

/**
 * Loads modules/hubTools.js and then the module under test, unmodified.
 * Throws when the module under test is absent or does not attach the
 * contract surface — which is the state of the repository at freeze time.
 */
function loadContract(options = {}) {
    const modulePath = path.join(ROOT, CONTRACT_MODULE);
    if (!fs.existsSync(modulePath)) {
        throw new Error(`module under test not found: ${CONTRACT_MODULE} (oracle frozen before implementation; must fail closed)`);
    }
    const moduleSource = fs.readFileSync(modulePath, 'utf8');
    const { sandbox, sink, clock } = createContractSandbox(options);
    vm.runInContext(fs.readFileSync(path.join(ROOT, HUB_TOOLS_MODULE), 'utf8'), sandbox, { filename: HUB_TOOLS_MODULE });
    vm.runInContext(moduleSource, sandbox, { filename: CONTRACT_MODULE });
    const contract = sandbox.HubTools && sandbox.HubTools.farmaciaActContract;
    if (!contract || typeof contract.createAct !== 'function') {
        throw new Error('module loaded but HubTools.farmaciaActContract.createAct is not a function');
    }
    return { create: contract.createAct, moduleSource, sandbox, clock };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function safeCreate(create, request) {
    try {
        return { result: create(request) };
    } catch (err) {
        return { threw: err };
    }
}

const sortedKeys = (obj) => Object.keys(obj).sort();

const describeValue = (v) => {
    if (typeof v === 'function') return 'function';
    if (typeof v === 'symbol') return 'symbol';
    try { return JSON.stringify(v) ?? String(v); } catch { return String(v); }
};

function isStructuredFailure(outcome) {
    if (outcome.threw) return false;
    const r = outcome.result;
    return !!r && typeof r === 'object'
        && r.ok === false
        && r.error && typeof r.error === 'object'
        && typeof r.error.code === 'string' && r.error.code.trim() !== ''
        && typeof r.error.message === 'string' && r.error.message !== ''
        && sortedKeys(r).join('|') === 'error|ok'
        // no fabricated act: no envelope field is exposed on a failure
        && BASE_ENVELOPE_KEYS.filter((k) => k !== 'ok').every((k) => r[k] === undefined)
        && r.amendment === undefined;
}

function isDeepCopiedFaithful(copy, original) {
    if (copy === original) return { pass: false, detail: 'same reference as input (not detached)' };
    if (typeof copy !== 'object' || copy === null || Array.isArray(copy)) return { pass: false, detail: 'copy is not an object' };
    if (sortedKeys(copy).join('|') !== sortedKeys(original).join('|')) return { pass: false, detail: `keys=${sortedKeys(copy).join('|')} expected=${sortedKeys(original).join('|')}` };
    if (JSON.stringify(copy) !== JSON.stringify(original)) return { pass: false, detail: 'not a faithful copy (JSON snapshot differs)' };
    return { pass: true, detail: '' };
}

function isOkActShape(result, request, expectAmendment) {
    if (!result || typeof result !== 'object' || result.ok !== true) return { pass: false, detail: 'result is not an ok result' };
    const expectedKeys = (expectAmendment ? WITH_AMENDMENT_KEYS : BASE_ENVELOPE_KEYS).join('|');
    if (sortedKeys(result).join('|') !== expectedKeys) return { pass: false, detail: `keys=${sortedKeys(result).join('|')} expected=${expectedKeys}` };
    if (result.contractVersion !== CONTRACT_VERSION) return { pass: false, detail: `contractVersion=${JSON.stringify(result.contractVersion)}` };
    const scalarFields = ['actId', 'revision', 'kind', 'siteId', 'patientRef', 'occurredAt', 'authoredAt', 'authorRef', 'attributionAssurance'];
    for (const f of scalarFields) {
        if (result[f] !== request[f]) return { pass: false, detail: `${f} not echoed verbatim` };
    }
    for (const f of ['payload', 'provenance']) {
        const check = isDeepCopiedFaithful(result[f], request[f]);
        if (!check.pass) return { pass: false, detail: `${f}: ${check.detail}` };
    }
    if (expectAmendment) {
        if (!request.amendment) return { pass: false, detail: 'oracle error: expectAmendment without input amendment' };
        const check = isDeepCopiedFaithful(result.amendment, request.amendment);
        if (!check.pass) return { pass: false, detail: `amendment: ${check.detail}` };
    }
    return { pass: true, detail: '' };
}

function attemptMutation(fn) {
    try {
        fn();
        return 'applied';
    } catch (err) {
        return `blocked (${err.constructor.name})`;
    }
}

const VALID_REQUEST = () => ({
    actId: 'ACT-SYN-0001',
    revision: 1,
    kind: 'pharmacy_validation',
    siteId: 'HUB-DEMO-SITE',
    patientRef: 'SYN-0001',
    occurredAt: '2026-09-30T10:00:00Z',
    authoredAt: '2026-09-30T12:00:00Z',
    authorRef: 'FH-SYN-AUTHOR-01',
    attributionAssurance: 'explicit_professional_authorship_synthetic',
    provenance: { source: 'synthetic-oracle', note: 'synthetic characterization data' },
    payload: { notaSintetica: 'SYN', numeroSintetico: 3, banderaSintetica: true },
});

const VALID_AMENDMENT = (revision) => ({ previousRevision: revision - 1, reason: 'synthetic correction reason' });

const SENTINEL_PAYLOAD = () => ({
    emptyString: '',
    na: 'NA',
    nd: 'ND',
    zero: 0,
    falseValue: false,
    nullValue: null,
    presentUndefined: undefined,
    nested: { hta: 'NA', counts: [0, false, '', 'ND', null], inner: { cero: 0, flag: false, ndToken: 'ND' } },
    lineas: [{ id: 1, activo: false }, { id: 2, na: 'NA', nd: 'ND' }],
});

const SENTINEL_PROVENANCE = () => ({
    empty: '',
    zero: 0,
    flag: false,
    nil: null,
    und: undefined,
    inner: { vacio: '', cero: 0 },
});

// ---------------------------------------------------------------------------
// Case families
// ---------------------------------------------------------------------------

function familyA(create, degradedDetail) {
    console.log('  Family A — acceptance: valid creation for the 3 kinds, exact envelope, detachment, amendment, no autogen metadata');
    for (const kind of KINDS) {
        const name = `A valid ${kind} creates an ok Pharmacy Act v1 (exact envelope, verbatim echo, detached payload/provenance)`;
        if (!create) { record(name, false, degradedDetail); continue; }
        const request = { ...VALID_REQUEST(), kind };
        const outcome = safeCreate(create, request);
        if (outcome.threw) { record(name, false, `threw: ${outcome.threw.message}`); continue; }
        const shape = isOkActShape(outcome.result, request, false);
        record(name, shape.pass, shape.detail);
    }
    if (create) {
        // Valid amendment: echoed verbatim, detached, key present.
        const requestA = { ...VALID_REQUEST(), revision: 3, amendment: VALID_AMENDMENT(3) };
        const outcomeA = safeCreate(create, requestA);
        const shapeA = outcomeA.threw ? { pass: false, detail: `threw: ${outcomeA.threw.message}` } : isOkActShape(outcomeA.result, requestA, true);
        record('A valid amendment { previousRevision < revision, reason } is echoed verbatim and detached', shapeA.pass, shapeA.detail);

        // Absent amendment: NO 'amendment' key at all (no null placeholder).
        const outcomeB = safeCreate(create, VALID_REQUEST());
        record('A absent amendment produces an ok act with NO amendment key (no null/undefined placeholder)',
            !outcomeB.threw && outcomeB.result && outcomeB.result.ok === true && !('amendment' in outcomeB.result),
            outcomeB.threw ? `threw: ${outcomeB.threw.message}` : `hasKey=${outcomeB.result ? 'amendment' in outcomeB.result : 'n/a'}`);

        // Shared-but-acyclic reference inside payload is legal input.
        const shared = { dato: 'SYN' };
        const requestS = { ...VALID_REQUEST(), payload: { a: shared, b: shared } };
        const outcomeS = safeCreate(create, requestS);
        const shapeS = outcomeS.threw ? { pass: false, detail: `threw: ${outcomeS.threw.message}` } : isOkActShape(outcomeS.result, requestS, false);
        record('A shared-but-acyclic references inside payload are accepted (copied, not treated as cycles)', shapeS.pass, shapeS.detail);

        // No autogenerated metadata: identical explicit input -> deep-identical acts.
        const r1 = safeCreate(create, VALID_REQUEST());
        const r2 = safeCreate(create, VALID_REQUEST());
        record('A no autogen metadata: two creations from identical explicit input are deep-identical',
            !r1.threw && !r2.threw && JSON.stringify(r1.result) === JSON.stringify(r2.result),
            r1.threw || r2.threw ? 'threw' : 'results differ');

        // Falsification self-test: a planted wrong expectation must be
        // detected as FAIL by the checker itself (oracle can disagree).
        const outcome = safeCreate(create, VALID_REQUEST());
        const shape = outcome.threw ? { pass: false } : isOkActShape(outcome.result, VALID_REQUEST(), false);
        plantedSink.length = 0;
        plantedRecord('planted lie: contractVersion is pharmacy-act/v9', shape.pass && outcome.result.contractVersion === 'pharmacy-act/v9', 'actual contractVersion differs (expected for the planted lie)');
        record('A-f planted lie (wrong contractVersion) is detected as false',
            plantedDetectedAsFalse(), plantedSummary());
    } else {
        record('A valid amendment is echoed verbatim and detached', false, degradedDetail);
        record('A absent amendment produces an ok act with NO amendment key', false, degradedDetail);
        record('A shared-but-acyclic references inside payload are accepted', false, degradedDetail);
        record('A no autogen metadata: two creations from identical explicit input are deep-identical', false, degradedDetail);
        record('A-f planted lie (wrong contractVersion) is detected as false', false, degradedDetail);
    }
}

const INVALID_KINDS = [
    ['missing', undefined],
    ['empty string', ''],
    ['whitespace only', '   '],
    ['upper case', 'PHARMACY_VALIDATION'],
    ['mixed case', 'Pharmacy_Validation'],
    ['dash instead of underscore', 'pharmacy-validation'],
    ['trailing whitespace', 'pharmacy_validation '],
    ['near-miss singular', 'pharmacy_validations'],
    ['descriptive synonym', 'validation'],
    ['spanish drift', 'validacion'],
    ['unknown kind', 'pharmacy_renewal'],
    ['null', null],
    ['number', 1],
    ['boolean', true],
    ['plain object', {}],
    ['array-wrapped token', ['pharmacy_followup']],
];

const INVALID_NON_EMPTY_STRINGS = [
    ['missing', undefined],
    ['empty string', ''],
    ['whitespace only', '   '],
    ['tab/newline only', '\t\n'],
    ['null', null],
    ['number', 42],
    ['zero', 0],
    ['boolean', true],
    ['array', ['SYN-0001']],
    ['object wrapper', { ref: 'SYN-0001' }],
    ['function', () => 'SYN-0001'],
];

const INVALID_REVISIONS = [
    ['missing', undefined],
    ['null', null],
    ['zero', 0],
    ['negative', -1],
    ['fractional', 1.5],
    ['numeric string', '1'],
    ['boolean true', true],
    ['NaN', NaN],
    ['Infinity', Infinity],
    ['array-wrapped', [1]],
    ['object wrapper', { revision: 1 }],
];

const INVALID_TIMESTAMPS = [
    ['missing', undefined],
    ['empty string', ''],
    ['whitespace only', '   '],
    ['date-only ISO', '2026-09-30'],
    ['locale format', '30/09/2026'],
    ['space instead of T', '2026-09-30 10:00:00'],
    ['relative token', 'now'],
    ['impossible month', '2026-13-01T10:00:00Z'],
    ['impossible day', '2026-02-30T10:00:00Z'],
    ['epoch number', 1727654400000],
    ['Date object', new Date(0)],
    ['null', null],
    ['boolean', true],
    ['array-wrapped', ['2026-09-30T10:00:00Z']],
];

const INVALID_OBJECT_FIELDS = [
    ['missing', undefined],
    ['null', null],
    ['empty array', []],
    ['array with entries', ['x']],
    ['empty string', ''],
    ['non-empty string', 'texto'],
    ['number', 42],
    ['zero', 0],
    ['boolean', true],
    ['function', () => {}],
];

const UNSUPPORTED_PAYLOAD_VALUES = [
    ['function value', () => ({ conFuncion: () => {} })],
    ['Date instance', () => ({ cuando: new Date(0) })],
    ['Map instance', () => ({ mapa: new Map() })],
    ['Set instance', () => ({ conjunto: new Set([1]) })],
    ['RegExp instance', () => ({ patron: /SYN/ })],
    ['symbol value', () => ({ simbolo: Symbol('SYN') })],
    ['bigint value', () => ({ grande: 10n })],
    ['NaN value', () => ({ noNumero: NaN })],
    ['Infinity value', () => ({ infinito: Infinity })],
    ['class instance', () => ({ instancia: new (class Cosa {})() })],
    ['direct cycle', () => { const o = { nota: 'SYN' }; o.self = o; return o; }],
    ['nested cycle', () => { const o = { a: { nota: 'SYN' } }; o.a.b = o; return o; }],
];

function familyB(create, degradedDetail) {
    console.log('  Family B — fail-closed: invalid kind/IDs/revision/timestamps/payload/provenance/amendment never fabricate an act');
    const groups = [
        ['kind', INVALID_KINDS],
        ['actId', INVALID_NON_EMPTY_STRINGS],
        ['siteId', INVALID_NON_EMPTY_STRINGS],
        ['patientRef', INVALID_NON_EMPTY_STRINGS],
        ['authorRef', INVALID_NON_EMPTY_STRINGS],
        ['attributionAssurance', INVALID_NON_EMPTY_STRINGS],
        ['revision', INVALID_REVISIONS],
        ['occurredAt', INVALID_TIMESTAMPS],
        ['authoredAt', INVALID_TIMESTAMPS],
        ['payload', INVALID_OBJECT_FIELDS],
        ['provenance', INVALID_OBJECT_FIELDS],
    ];
    for (const [field, cases] of groups) {
        for (const [label, badValue] of cases) {
            const name = `B ${field}=${label} (${describeValue(badValue)}) fails closed with a typed structured error`;
            if (!create) { record(name, false, degradedDetail); continue; }
            const request = VALID_REQUEST();
            request[field] = badValue;
            const outcome = safeCreate(create, request);
            record(name, isStructuredFailure(outcome), outcome.threw
                ? `threw instead of structured failure: ${outcome.threw.message}`
                : `result=${JSON.stringify(outcome.result)}`);
        }
    }
    // Unsupported value types / cycles inside payload and provenance.
    for (const [label, build] of UNSUPPORTED_PAYLOAD_VALUES) {
        for (const field of ['payload', 'provenance']) {
            const name = `B ${field} with ${label} fails closed (never normalized silently)`;
            if (!create) { record(name, false, degradedDetail); continue; }
            const request = VALID_REQUEST();
            request[field] = build();
            const outcome = safeCreate(create, request);
            record(name, isStructuredFailure(outcome), outcome.threw
                ? `threw instead of structured failure: ${outcome.threw.message}`
                : `result=${JSON.stringify(outcome.result)}`);
        }
    }
    const INVALID_AMENDMENTS = [
        ['null', null],
        ['empty string', ''],
        ['non-empty string', 'texto'],
        ['number', 42],
        ['array', []],
        ['array-wrapped object', [{ previousRevision: 2, reason: 'SYN' }]],
        ['function', () => ({})],
        ['missing previousRevision', { reason: 'SYN' }],
        ['missing reason', { previousRevision: 2 }],
        ['empty object', {}],
        ['previousRevision equal to revision', { previousRevision: 3, reason: 'SYN' }],
        ['previousRevision greater than revision', { previousRevision: 4, reason: 'SYN' }],
        ['previousRevision zero', { previousRevision: 0, reason: 'SYN' }],
        ['previousRevision negative', { previousRevision: -1, reason: 'SYN' }],
        ['previousRevision fractional', { previousRevision: 2.5, reason: 'SYN' }],
        ['previousRevision numeric string', { previousRevision: '2', reason: 'SYN' }],
        ['empty reason', { previousRevision: 2, reason: '' }],
        ['whitespace-only reason', { previousRevision: 2, reason: '   ' }],
        ['non-string reason', { previousRevision: 2, reason: 42 }],
        ['extra key', { previousRevision: 2, reason: 'SYN', extra: 1 }],
    ];
    for (const [label, badAmendment] of INVALID_AMENDMENTS) {
        const name = `B amendment=${label} fails closed with a typed structured error`;
        if (!create) { record(name, false, degradedDetail); continue; }
        const request = { ...VALID_REQUEST(), revision: 3, amendment: badAmendment };
        const outcome = safeCreate(create, request);
        record(name, isStructuredFailure(outcome), outcome.threw
            ? `threw instead of structured failure: ${outcome.threw.message}`
            : `result=${JSON.stringify(outcome.result)}`);
    }
    if (create) {
        const request = VALID_REQUEST();
        request.kind = 'no-existe';
        const outcome = safeCreate(create, request);
        plantedSink.length = 0;
        plantedRecord('planted lie: invalid kind is accepted with ok===true', !outcome.threw && outcome.result && outcome.result.ok === true, 'invalid input is rejected (expected for the planted lie)');
        record('B-f planted lie (invalid kind accepted) is detected as false',
            plantedDetectedAsFalse(), plantedSummary());
    } else {
        record('B-f planted lie (invalid kind accepted) is detected as false', false, degradedDetail);
    }
}

const C_CASE_NAMES = [
    'C ok result obtained for the sentinel payload',
    'C no key dropped (key set identical, including presentUndefined)',
    'C key-present-with-undefined stays present-with-undefined',
    "C '' preserved verbatim",
    "C 'NA' preserved verbatim",
    "C 'ND' preserved verbatim",
    'C 0 preserved as number',
    'C false preserved as boolean',
    "C null preserved as null (distinct from undefined and '')",
    'C nested objects/arrays deep-copied (new references)',
    'C nested sentinels preserved verbatim',
    'C defined content JSON-identical to the input payload',
    'C provenance sentinels preserved (missing/null/\'\'/0/false/undefined distinct)',
    'C provenance key set identical (no key dropped, no key added)',
];

function familyC(create, degradedDetail) {
    console.log('  Family C — sentinel preservation: no collapse, no dropped keys, deep copy (payload + provenance)');
    if (!create) {
        for (const name of C_CASE_NAMES) record(name, false, degradedDetail);
        return;
    }
    const sentinels = SENTINEL_PAYLOAD();
    const provenance = SENTINEL_PROVENANCE();
    const request = { ...VALID_REQUEST(), kind: 'pharmacy_followup', payload: sentinels, provenance };
    const outcome = safeCreate(create, request);
    const act = (!outcome.threw && outcome.result && outcome.result.ok === true) ? outcome.result : null;
    record(C_CASE_NAMES[0], !!act, outcome.threw ? `threw: ${outcome.threw.message}` : `result=${JSON.stringify(outcome.result)}`);
    if (act) {
        const p = act.payload;
        record(C_CASE_NAMES[1], sortedKeys(p).join('|') === sortedKeys(sentinels).join('|'),
            `keys=${sortedKeys(p).join('|')}`);
        record(C_CASE_NAMES[2], 'presentUndefined' in p && p.presentUndefined === undefined,
            `present=${'presentUndefined' in p} value=${p.presentUndefined}`);
        record(C_CASE_NAMES[3], p.emptyString === '', `value=${JSON.stringify(p.emptyString)}`);
        record(C_CASE_NAMES[4], p.na === 'NA', `value=${JSON.stringify(p.na)}`);
        record(C_CASE_NAMES[5], p.nd === 'ND', `value=${JSON.stringify(p.nd)}`);
        record(C_CASE_NAMES[6], p.zero === 0 && typeof p.zero === 'number', `value=${JSON.stringify(p.zero)}`);
        record(C_CASE_NAMES[7], p.falseValue === false && typeof p.falseValue === 'boolean', `value=${JSON.stringify(p.falseValue)}`);
        record(C_CASE_NAMES[8], p.nullValue === null, `value=${JSON.stringify(p.nullValue)}`);
        record(C_CASE_NAMES[9],
            p.nested !== sentinels.nested && p.nested.inner !== sentinels.nested.inner
            && p.lineas !== sentinels.lineas && p.lineas[0] !== sentinels.lineas[0],
            'nested references must be new objects/arrays');
        record(C_CASE_NAMES[10],
            p.nested && p.nested.hta === 'NA'
            && p.nested.inner && p.nested.inner.cero === 0 && p.nested.inner.flag === false && p.nested.inner.ndToken === 'ND'
            && Array.isArray(p.nested.counts)
            && p.nested.counts.length === 5 && p.nested.counts[0] === 0 && p.nested.counts[1] === false
            && p.nested.counts[2] === '' && p.nested.counts[3] === 'ND' && p.nested.counts[4] === null
            && p.lineas[0].activo === false && p.lineas[1].na === 'NA' && p.lineas[1].nd === 'ND',
            `nested=${JSON.stringify(p.nested)} lineas=${JSON.stringify(p.lineas)}`);
        record(C_CASE_NAMES[11], JSON.stringify(p) === JSON.stringify(sentinels), 'JSON snapshot of defined content differs');
        const pv = act.provenance;
        record(C_CASE_NAMES[12],
            pv.empty === '' && pv.zero === 0 && pv.flag === false && pv.nil === null
            && ('und' in pv) && pv.und === undefined
            && pv.inner && pv.inner.vacio === '' && pv.inner.cero === 0
            && pv.inner !== provenance.inner,
            `provenance=${JSON.stringify(pv)}`);
        record(C_CASE_NAMES[13], sortedKeys(pv).join('|') === sortedKeys(provenance).join('|'),
            `keys=${sortedKeys(pv).join('|')}`);
        plantedSink.length = 0;
        plantedRecord("planted lie: 'NA' collapses to 'ND'", p.na === 'ND', 'NA is preserved (expected for the planted lie)');
        record('C-f planted lie (sentinel collapse) is detected as false',
            plantedDetectedAsFalse(), plantedSummary());
    } else {
        for (const name of C_CASE_NAMES.slice(1)) record(name, false, 'no ok act payload to inspect');
        plantedSink.length = 0;
        plantedRecord('planted lie (sentinel collapse) skipped in degraded mode', false, 'degraded');
        record('C-f planted lie (sentinel collapse) is detected as false', plantedDetectedAsFalse(), plantedSummary());
    }
}

const D_CASE_NAMES = [
    'D ok act created from the D request',
    'D input request left deep-identical after creation (JSON snapshot)',
    'D input nested reference identity preserved (payload/provenance/amendment untouched)',
    'D returned payload/provenance/amendment are new detached objects (different references)',
    'D mutating the returned act does not affect the inputs (JSON + references)',
    'D mutating the inputs after creation does not affect the returned act',
];

function familyD(create, degradedDetail) {
    console.log('  Family D — no-mutation + immutability: detachment proven in both directions (payload/provenance/amendment)');
    if (!create) {
        for (const name of D_CASE_NAMES) record(name, false, degradedDetail);
        return;
    }
    const payloadD = {
        nota: 'sintetica',
        numero: 3,
        bandera: false,
        vacio: '',
        presente: undefined,
        anidado: { nivel: { cero: 0, na: 'NA' } },
        lineas: [{ id: 1, activo: false }, { id: 2 }],
    };
    const provenanceD = { origen: 'SYN', detalle: { cero: 0, vacio: '' } };
    const request = {
        ...VALID_REQUEST(),
        kind: 'pharmacy_first_visit',
        revision: 2,
        payload: payloadD,
        provenance: provenanceD,
        amendment: { previousRevision: 1, reason: 'SYN' },
    };
    const requestSnapshotBefore = JSON.stringify(request);
    const refs = {
        request,
        payload: payloadD,
        anidado: payloadD.anidado,
        nivel: payloadD.anidado.nivel,
        lineas: payloadD.lineas,
        lineas0: payloadD.lineas[0],
        provenance: provenanceD,
        detalle: provenanceD.detalle,
        amendment: request.amendment,
    };
    const outcome = safeCreate(create, request);
    const act = (!outcome.threw && outcome.result && outcome.result.ok === true) ? outcome.result : null;
    record(D_CASE_NAMES[0], !!act, outcome.threw ? `threw: ${outcome.threw.message}` : `result=${JSON.stringify(outcome.result)}`);
    if (!act) {
        for (const name of D_CASE_NAMES.slice(1)) record(name, false, 'no ok act to verify');
        return;
    }
    record(D_CASE_NAMES[1], JSON.stringify(request) === requestSnapshotBefore, 'input request snapshot changed');
    record(D_CASE_NAMES[2],
        refs.request === request && refs.payload === payloadD && refs.anidado === payloadD.anidado
        && refs.nivel === payloadD.anidado.nivel && refs.lineas === payloadD.lineas && refs.lineas0 === payloadD.lineas[0]
        && refs.provenance === provenanceD && refs.detalle === provenanceD.detalle && refs.amendment === request.amendment,
        'input nested references changed');
    record(D_CASE_NAMES[3],
        act.payload !== payloadD && act.payload.anidado !== payloadD.anidado && act.payload.lineas !== payloadD.lineas
        && act.provenance !== provenanceD && act.provenance.detalle !== provenanceD.detalle
        && act.amendment !== request.amendment,
        'act shares references with the input');
    // Probe 1 — caller mutates the returned act (only detachment is
    // guaranteed): the INPUTS must remain unaffected.
    const inputSnapshotAtCreate = JSON.stringify(request);
    const mutationOnAct = attemptMutation(() => {
        act.payload.anidado.nivel.cero = 999;
        act.payload.lineas.push({ id: 3 });
        act.payload.extra = 'mutado';
        act.provenance.detalle.cero = 999;
        act.amendment.reason = 'mutado';
        act.amendment.extra = 'mutado';
        act.patientRef = 'SYN-HACKED';
        act.kind = 'pharmacy_validation';
    });
    record(D_CASE_NAMES[4],
        JSON.stringify(request) === inputSnapshotAtCreate
        && refs.anidado === payloadD.anidado && refs.nivel === payloadD.anidado.nivel
        && refs.lineas === payloadD.lineas && refs.lineas0 === payloadD.lineas[0]
        && payloadD.anidado.nivel.cero === 0 && payloadD.lineas.length === 2 && !('extra' in payloadD)
        && provenanceD.detalle.cero === 0
        && !('extra' in refs.amendment) && refs.amendment.reason === 'SYN',
        `actMutation=${mutationOnAct}`);
    // Probe 2 — caller mutates the INPUTS after creation: the act must remain
    // exactly as it was when handed over.
    const actPayloadBaseline = JSON.stringify(act.payload);
    const actProvenanceBaseline = JSON.stringify(act.provenance);
    const actAmendmentBaseline = JSON.stringify(act.amendment);
    const actScalarBaseline = { kind: act.kind, patientRef: act.patientRef, contractVersion: act.contractVersion, revision: act.revision };
    const mutationOnInputs = attemptMutation(() => {
        payloadD.anidado.nivel.cero = -1;
        payloadD.lineas.shift();
        payloadD.extra = 'despues';
        provenanceD.detalle.cero = -1;
        request.amendment.reason = 'cambiado';
        request.patientRef = 'SYN-CAMBIADO';
        request.kind = 'pharmacy_validation';
        request.revision = 9;
    });
    record(D_CASE_NAMES[5],
        JSON.stringify(act.payload) === actPayloadBaseline
        && JSON.stringify(act.provenance) === actProvenanceBaseline
        && JSON.stringify(act.amendment) === actAmendmentBaseline
        && act.kind === actScalarBaseline.kind && act.patientRef === actScalarBaseline.patientRef
        && act.contractVersion === actScalarBaseline.contractVersion && act.revision === actScalarBaseline.revision,
        `inputMutation=${mutationOnInputs}`);
}

const E_FORBIDDEN_SUBSTRINGS = [
    ['FarmaciaExportV2Core', 'Export v2 core module'],
    ['ROW_COLUMNS', 'transport row column constant'],
    ['ROW_SCHEMA_VERSION', 'transport row schema constant'],
    ['row_id', 'transport row identifier'],
    ['row_index', 'transport row index'],
    ['row_count', 'transport row count'],
    ['row_role', 'transport row role'],
    ['bridge_status', 'bridge transport status'],
    ['HubTools.export', 'transport export namespace'],
    ['HubTools.data', 'data namespace (contract must not read patient state)'],
];

const E_FORBIDDEN_PATTERNS = [
    [/\bTSV\b/i, 'TSV transport'],
    [/clipboard/i, 'clipboard transport'],
    [/\bexcel\b/i, 'Excel transport'],
    [/\bworksheet\b/i, 'worksheet transport'],
    [/\bsharepoint\b/i, 'SharePoint backend'],
    [/\bSQL\b/, 'SQL backend'],
    [/\bcommit\s*\(/, 'public commit(event) surface'],
    [/\bDate\s*\.\s*now\b/, 'automatic timestamp generation'],
    [/\bMath\s*\.\s*random\b/, 'randomness (non-deterministic metadata)'],
    [/\blocalStorage\b/, 'browser storage'],
    [/\bsessionStorage\b/, 'browser storage'],
    [/\bdocument\b/, 'DOM access'],
    [/\bgetElementById\b/, 'DOM access'],
    [/\bimport\s*[\{('"]/, 'ESM import statement'],
    [/(^|\n)\s*import\s/, 'ESM import statement'],
    [/\brequire\s*\(/, 'CommonJS require'],
];

const E_CASE_NAMES = [
    'E module under test exists and is readable',
    ...E_FORBIDDEN_SUBSTRINGS.map(([token]) => `E source contains no '${token}'`),
    ...E_FORBIDDEN_PATTERNS.map(([, why]) => `E source contains no ${why} pattern`),
    'E module exposes HubTools.farmaciaActContract.createAct in the sandbox',
    'E HubTools.export stays empty after loading the contract (no transport wiring)',
    'E contract does not create HubTools.farmaciaExportV2Core or any other new HubTools namespace',
    'E creating an act never calls Date.now() or new Date() (no autogenerated metadata, instrumented clock)',
];

function familyE(create, sandbox, moduleSource, degradedDetail) {
    console.log('  Family E — transport ignorance + no autogenerated metadata: static + behavioral independence');
    if (!moduleSource) {
        record(E_CASE_NAMES[0], false, degradedDetail);
        for (const name of E_CASE_NAMES.slice(1)) record(name, false, 'module under test unavailable');
        return;
    }
    record(E_CASE_NAMES[0], true, `${moduleSource.length} chars`);
    let i = 1;
    for (const [token] of E_FORBIDDEN_SUBSTRINGS) {
        record(E_CASE_NAMES[i++], !moduleSource.includes(token), `occurrences=${moduleSource.split(token).length - 1}`);
    }
    for (const [pattern, why] of E_FORBIDDEN_PATTERNS) {
        const match = moduleSource.match(pattern);
        record(E_CASE_NAMES[i++], !match, match ? `matched '${match[0].replace(/\n/g, '\\n')}' (${why})` : 'no match');
    }
    if (sandbox) {
        record(E_CASE_NAMES[i++], !!sandbox.HubTools.farmaciaActContract && typeof sandbox.HubTools.farmaciaActContract.createAct === 'function', 'contract surface missing');
        record(E_CASE_NAMES[i++], !!sandbox.HubTools.export && typeof sandbox.HubTools.export === 'object' && Object.keys(sandbox.HubTools.export).length === 0,
            `HubTools.export keys=${sandbox.HubTools.export ? Object.keys(sandbox.HubTools.export).join(',') : 'n/a'}`);
        const expectedNamespaces = new Set(['utils', 'scores', 'homunculus', 'data', 'normalizer', 'export', 'form', 'catalog', 'prebiologic', 'ui', 'pharmacy', 'events', 'dashboard', 'farmaciaActContract']);
        const unexpected = Object.keys(sandbox.HubTools).filter((k) => !expectedNamespaces.has(k));
        record(E_CASE_NAMES[i++], sandbox.HubTools.farmaciaExportV2Core === undefined && unexpected.length === 0,
            `unexpected=${unexpected.join(',')}`);
    } else {
        record(E_CASE_NAMES[i++], false, 'contract surface unavailable');
        record(E_CASE_NAMES[i++], false, 'contract surface unavailable');
        record(E_CASE_NAMES[i++], false, 'contract surface unavailable');
    }
    // Behavioral no-autogen: instrumented Date must never be consulted.
    let clockCalls = -1;
    try {
        const instrumented = loadContract({ instrumentClock: true });
        const outcome = safeCreate(instrumented.create, { ...VALID_REQUEST(), revision: 2, kind: 'pharmacy_followup', amendment: VALID_AMENDMENT(2) });
        clockCalls = instrumented.clock.nowCalls + instrumented.clock.ctorCalls;
        record(E_CASE_NAMES[i++], !outcome.threw && outcome.result && outcome.result.ok === true && clockCalls === 0,
            outcome.threw ? `threw: ${outcome.threw.message}` : `clockCalls=${clockCalls}`);
    } catch (err) {
        record(E_CASE_NAMES[i++], false, `instrumented load failed: ${err.message}`);
    }
    plantedSink.length = 0;
    plantedRecord('planted lie: contract source references the row transport', moduleSource.includes('row_id'), 'source is clean (expected for the planted lie)');
    record('E-f planted lie (transport reference) is detected as false',
        plantedDetectedAsFalse(), plantedSummary());
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
    console.log('Pharmacy Act v1 contract oracle (WO-NEXUS-FARMACIA-F4.4A, #488, 100% synthetic data)');

    let create = null;
    let moduleSource = null;
    let sandbox = null;
    let degradedDetail = '';
    try {
        ({ create, moduleSource, sandbox } = loadContract());
    } catch (err) {
        degradedDetail = `module under test unavailable: ${err.message}`;
        console.log(`  [FAIL] LOAD ${CONTRACT_MODULE} loads in the vm sandbox and exposes HubTools.farmaciaActContract.createAct -> ${degradedDetail}`);
        results.push({ name: 'LOAD', pass: false });
    }

    familyA(create, degradedDetail);
    familyB(create, degradedDetail);
    familyC(create, degradedDetail);
    familyD(create, degradedDetail);
    familyE(create, sandbox, moduleSource, degradedDetail);

    const failed = results.filter((r) => !r.pass).length;
    console.log('');
    console.log(`RESULTADO: ${results.length - failed} OK / ${failed} FALLIDO`);
    if (failed > 0) {
        console.error('Farmacia act contract check FAILED');
        process.exit(1);
    }
    console.log('Farmacia act contract check PASSED');
}

main();
