#!/usr/bin/env node

import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputs = require(path.join(ROOT, 'scripts/farmacia_followup_outputs_v4.js'));
const visits = require(path.join(ROOT, 'scripts/farmacia_followup_confirmed_visit_v4.js'));
const outputSource = fs.readFileSync(path.join(ROOT, 'scripts/farmacia_followup_outputs_v4.js'), 'utf8');
const contextSource = fs.readFileSync(path.join(ROOT, 'scripts/farmacia_followup_context_v4.js'), 'utf8');
const legacySource = fs.readFileSync(path.join(ROOT, 'scripts/farmacia_seguimiento.js'), 'utf8');
const excelSource = fs.readFileSync(path.join(ROOT, 'scripts/farmacia_excel_row_export.js'), 'utf8');
const html = fs.readFileSync(path.join(ROOT, 'farmacia_seguimiento.html'), 'utf8');
let passed = 0;
const tests = [];
function test(name, fn) { tests.push({ name, fn }); }
function uuid(number) { return `00000000-0000-4000-8000-${String(number).padStart(12, '0')}`; }
function record(number = 1, patient = 'patient-a', line = 'line-a', confirmedAt = '2026-07-26T10:00:00.000Z', patch = {}) {
  return { record_id: uuid(number), patient_id: patient, line_id: line, visit_date: '2026-07-26', confirmed_at: confirmedAt,
    confirmed_by_demo: 'Profesional FH-01', source_draft_saved_at: `2026-07-26T0${number}:00:00.000Z`, source_draft_saved_by_demo: 'Profesional FH-01',
    notes: 'Confirmado exacto', mg1: 'si', mg2: 'no', mg3: '', mg4: '', ae_present: 'si', ae_description: 'EA demo', ae_severity: 'leve',
    ae_resolution: 'en_seguimiento', proms_collected: 'si', dlqi_total: 0, eva_dolor: 0, eva_prurito: '', ...patch };
}
function visitState(...items) { const state = visits.emptyState(); for (const item of items) state.records[item.record_id] = item; return state; }
function memory(raw, options = {}) { return { getItem(key) { if (options.throwRead) throw new Error('denied'); return key === visits.STORE_KEY ? raw : null; }, setItem() {}, removeItem() {} }; }
function node(id) { return { id, textContent: '', value: '', disabled: false, inert: false, attributes: {}, setAttribute(name, value) { this.attributes[name] = String(value); }, removeAttribute(name) { delete this.attributes[name]; } }; }
const IDS = ['modExportacion', 'fhSegOutputStatus', ...Object.values(outputs.AUDIT_IDS), ...Object.keys(outputs.TARGETS)];
function context(overrides = {}) { return { ok: true, code: 'CANONICAL_ACTIVE_CONTEXT_READY', patient_id: 'patient-a', line_id: 'line-a', source: 'FarmaciaDataSource',
  person: { cip: 'CIP-CANONICAL', service: 'Dermatología', pathology: 'Patología sintética' }, request: null, validation_act: null, start_movement: null,
  line: { patient_id: 'patient-a', line_id: 'line-a', status: 'active', relationship: 'primary', provenance: 'pre_hub_existing', drug_name: 'Fármaco explícito',
    active_ingredient: '', dose_text: '', presentation: '', route: '', pauta_codigo: '', pauta_label: '', pauta_otro_texto: '', start_date: '2026-01-02' }, ...overrides };
}
function helper(captures, options = {}) { return { WO8_COLUMNS: Array.from({ length: 61 }, (_, i) => `c${i}`),
  buildExcelRowObject(value) { captures.excelContext = value; return {}; }, buildExcelRowArray(row) { captures.excelRow = row; return Array.from({ length: options.columns || 61 }, (_, i) => row[`c${i}`] || ''); },
  toTSVRow(row) { captures.excelArray = row; return row.join('\t'); }, copyTSVRowToClipboard() { captures.excelHelperCopies += 1; return true; }, getServiceSheetName() { return '01_DERMA'; } }; }
function actualExcelHelper() { const sandbox = { window: {}, navigator: { clipboard: { writeText() { return Promise.resolve(); } } }, document: {} }; vm.runInNewContext(excelSource, sandbox); return sandbox.window.FarmaciaExcelRowExport; }
function fixture({ records = [record()], contextValue = context(), raw, storageOptions, helperOptions, search = '?cip=CIP-URL&patient_id=patient-a&line_id=line-a' } = {}) {
  const elements = Object.fromEntries(IDS.map((id) => [id, node(id)])); const captures = { copies: [], downloads: [], clipboardWrites: [], excelHelperCopies: 0 };
  const stateRaw = raw === undefined ? JSON.stringify(visitState(...records)) : raw;
  const resolved = contextValue;
  const env = { location: { search }, URLSearchParams, sessionStorage: memory(stateRaw, storageOptions),
    navigator: { clipboard: { writeText(value) { captures.clipboardWrites.push(value); if (helperOptions?.failClipboard) return Promise.reject(new Error('denied')); if (helperOptions?.deferClipboard) return new Promise((resolve) => { captures.resolveClipboard = resolve; }); return Promise.resolve(); } } },
    FarmaciaFollowupConfirmedVisitV4: visits,
    FarmaciaFollowupContextV4: { STORE_KEY: 'farmaciaDemo.multitreatment.v1', readIdentity(value) { const p = new URLSearchParams(value); return { patient_id: p.get('patient_id') || '', line_id: p.get('line_id') || '', cip: p.get('cip') || '' }; }, resolveCanonicalContext() { return typeof resolved === 'function' ? resolved() : resolved; } },
    FarmaciaDemo: { copyTextToClipboard(value) { captures.copies.push(value); if (helperOptions?.failCopy) return false; return true; }, downloadFile(name, value, type) { captures.downloads.push({ name, value, type }); if (helperOptions?.throwDownload) throw new Error('download failed'); if (helperOptions?.failDownload) return false; return true; } },
    FarmaciaExcelRowExport: helper(captures, helperOptions), FarmaciaDataSource: {}, FarmaciaMultitreatmentCore: {},
    document: { getElementById(id) { return elements[id] || null; } } };
  return { env, elements, captures, controller: outputs.createController(env, { now: () => '2026-07-26T12:34:56.000Z' }) };
}

test('projection has the exact 42-field CSV order', () => assert.deepEqual(outputs.CSV_COLUMNS, ['record_id','patient_id','cip_demo_o_hash','service','pathology','line_id','visit_date','confirmed_at','confirmed_by_demo','source_draft_saved_at','source_draft_saved_by_demo','context_source','line_status','relationship','provenance','drug_name','active_ingredient','dose_text','presentation','route','pauta_codigo','pauta_label','pauta_otro_texto','start_date','request_id','validation_act_id','start_movement_id','notes','mg1','mg2','mg3','mg4','ae_present','ae_description','ae_severity','ae_resolution','proms_collected','dlqi_total','eva_dolor','eva_prurito','generated_at','demo_flag']));
test('context blocked and empty visit use exact visible states', () => { const blocked = fixture({ contextValue: { ok: false, code: 'LINE_NOT_ACTIVE' } }); assert.equal(blocked.controller.refresh().code, 'FOLLOWUP_OUTPUT_CONTEXT_BLOCKED'); const empty = fixture({ records: [] }); assert.equal(empty.controller.refresh().code, 'FOLLOWUP_OUTPUT_EMPTY'); assert.equal(empty.elements.fhSegOutputStatus.textContent, outputs.TEXTS.FOLLOWUP_OUTPUT_EMPTY); });
test('corrupt incompatible ambiguous and unavailable confirmed stores fail closed', () => { const ambiguous = visitState(record(1), record(2, 'patient-a', 'line-a', '2026-07-26T10:00:00.000Z')); for (const item of [fixture({ raw: '{' }), fixture({ raw: JSON.stringify({ schema: 'wrong', records: {} }) }), fixture({ raw: JSON.stringify(ambiguous) }), fixture({ storageOptions: { throwRead: true } })]) assert.equal(item.controller.refresh().code, 'FOLLOWUP_OUTPUT_STORAGE_ERROR'); });
test('historical S10, PATIENT_NOT_FOUND and PATIENT_MISMATCH remain blocked', () => { for (const code of ['LINE_NOT_ACTIVE', 'PATIENT_NOT_FOUND', 'PATIENT_MISMATCH']) assert.equal(fixture({ contextValue: { ok: false, code } }).controller.refresh().code, 'FOLLOWUP_OUTPUT_CONTEXT_BLOCKED'); });
test('both S11 lines are isolated and never use the other partition', () => { const records = [record(1, 'patient-a', 'line-primary', undefined, { notes: 'primary' }), record(2, 'patient-a', 'line-additional', '2026-07-26T11:00:00.000Z', { notes: 'additional' })]; for (const [line, notes] of [['line-primary', 'primary'], ['line-additional', 'additional']]) { const selected = context({ line_id: line, line: { ...context().line, line_id: line } }); const value = fixture({ records, contextValue: selected, search: `?cip=CIP&patient_id=patient-a&line_id=${line}` }); assert.equal(value.controller.refresh().record.notes, notes); } });
test('latest exact visit is selected by confirmed_at rather than insertion or visit date', () => { const value = fixture({ records: [record(3, undefined, undefined, '2026-07-26T09:00:00.000Z', { notes: 'old', visit_date: '2026-07-30' }), record(4, undefined, undefined, '2026-07-26T11:00:00.000Z', { notes: 'latest', visit_date: '2026-07-20' })] }); assert.equal(value.controller.refresh().record.notes, 'latest'); });
test('URL CIP already validated by context wins and person fields are canonical only', () => { const value = fixture(); const result = value.controller.refresh().record; assert.deepEqual([result.cip_demo_o_hash, result.service, result.pathology], ['CIP-URL', 'Dermatología', 'Patología sintética']); });
test('missing values stay empty and valid PROM zero remains numeric zero', () => { const result = fixture().controller.refresh().record; assert.deepEqual([result.active_ingredient, result.eva_prurito], ['', '']); assert.strictEqual(result.dlqi_total, 0); assert.strictEqual(result.eva_dolor, 0); });
test('TXT has required banner and human absence without interpretation or legacy payload', () => { const txt = outputs.buildTxt(fixture().controller.refresh().record); assert.match(txt, /^DATOS SINTÉTICOS \/ DEMO — TEXTO PARA REVISIÓN, SIN INTEGRACIÓN JARA/); assert.match(txt, /Principio activo: No informado/); assert.match(txt, /MG1 \(respuesta cruda\): si/); assert.doesNotMatch(txt, /Morisky-Green|Naranjo|Karch|fármaco sospechoso|acción EA|movimiento terapéutico|resultado Morisky/i); });
test('CSV is exact one header plus one row with escaping blanks and zero', () => { const value = fixture(); const csv = outputs.buildCsv(value.controller.refresh().record); assert.equal(csv.split('\n').length, 2); assert.equal(csv.split('\n')[0].split(',').length, 42); assert.match(csv, /"Confirmado exacto"/); assert.match(csv, /,"0","0","",/); });
test('CSV filename is stable from visit date and record ID only', () => assert.equal(outputs.safeFilename(fixture().controller.refresh().record), `seguimiento_2026-07-26_${uuid(1)}.csv`));
test('Excel is 61 columns with exact identity audit raw MG zero and excluded fields blank', () => { const value = fixture(); const projection = value.controller.refresh().record; const excel = outputs.buildExcel(projection, value.env); assert.equal(excel.rowArray.length, 61); const row = excel.rowObject; assert.deepEqual([value.captures.excelContext.patientId, value.captures.excelContext.visitaId, value.captures.excelContext.fechaActo, value.captures.excelContext.profesional], ['patient-a', uuid(1), '2026-07-26', 'Profesional FH-01']); assert.equal(value.captures.excelContext.tipoActo, 'seguimiento'); assert.equal(value.captures.excelContext.estadoRegistro, 'confirmado_demo'); assert.equal(row.adherencia_morisky, 'mg1=si | mg2=no | mg3= | mg4='); assert.deepEqual([row.eva_dolor, row.dlqi], ['0', '0']); for (const field of ['tipo_movimiento','motivo_inicio_cambio_suspension','farmaco_sospechoso_id','farmaco_sospechoso_nombre','causalidad_naranjo','causalidad_karch','accion_ea','respuesta_clinica']) assert.equal(row[field], ''); assert.equal(row.created_at, projection.generated_at); assert.equal(row.updated_at, projection.generated_at); assert.match(row.observaciones_generales, /source_draft_saved_at=.*proms_collected=si.*eva_prurito=.*ae_resolution=en_seguimiento/); });
test('unchanged production FarmaciaExcelRowExport builds exactly 61 mapped columns and leaves es_principal empty', () => { const value = fixture(); value.env.FarmaciaExcelRowExport = actualExcelHelper(); const excel = outputs.buildExcel(value.controller.refresh().record, value.env); assert.equal(value.env.FarmaciaExcelRowExport.WO8_COLUMNS.length, 61); assert.equal(excel.rowArray.length, 61); const index = (name) => value.env.FarmaciaExcelRowExport.WO8_COLUMNS.indexOf(name); assert.deepEqual([excel.rowArray[index('patient_id')], excel.rowArray[index('fecha_acto')], excel.rowArray[index('visita_id')], excel.rowArray[index('linea_id')], excel.rowArray[index('estado_registro')]], ['patient-a','2026-07-26',uuid(1),'line-a','confirmado_demo']); assert.equal(excel.rowArray[index('adherencia_morisky')], 'mg1=si | mg2=no | mg3= | mg4='); assert.equal(excel.rowArray[index('es_principal')], ''); assert.equal(excel.rowArray[index('tipo_movimiento')], ''); assert.equal(excel.rowArray[index('causalidad_naranjo')], ''); assert.equal(excel.rowArray[index('accion_ea')], ''); });
test('TXT CSV and Excel executions await real Promise success and share exact confirmed identity', async () => { const value = fixture(); const results = []; for (const kind of ['txt', 'csv', 'excel']) results.push(await value.controller.execute(kind)); for (const item of results) assert.deepEqual([item.record.record_id, item.record.patient_id, item.record.line_id, item.record.visit_date, item.record.confirmed_by_demo], [uuid(1), 'patient-a', 'line-a', '2026-07-26', 'Profesional FH-01']); assert.equal(value.captures.copies.length, 0); assert.equal(value.captures.downloads.length, 1); assert.equal(value.captures.clipboardWrites.length, 2); assert.equal(value.captures.excelHelperCopies, 0); });
test('dirty only warns and cannot change any output payload', async () => { const value = fixture(); const clean = []; for (const kind of ['txt','csv','excel']) clean.push((await value.controller.execute(kind)).record); assert.equal(value.controller.applyDraftState({ dirty: true }).code, 'FOLLOWUP_OUTPUT_READY_WITH_UNSAVED_CHANGES'); value.env.poisonDraft = { notes: 'DIRTY POISON', mg1: 'no' }; const dirty = []; for (const kind of ['txt','csv','excel']) dirty.push((await value.controller.execute(kind)).record); assert.deepEqual(dirty, clean); assert.equal(value.elements.fhSegOutputStatus.attributes['data-status-code'], 'FOLLOWUP_OUTPUT_GENERATED'); });
test('same identity blocked to active refreshes and reload resolves from store', () => { let active = false; const value = fixture(); value.env.FarmaciaFollowupContextV4.resolveCanonicalContext = () => active ? context() : { ok: false, code: 'HUB_GRAPH_INCOHERENT' }; assert.equal(value.controller.refresh().code, 'FOLLOWUP_OUTPUT_CONTEXT_BLOCKED'); active = true; assert.equal(value.controller.refresh().code, 'FOLLOWUP_OUTPUT_READY'); const reloaded = fixture(); assert.equal(reloaded.controller.refresh().record.record_id, uuid(1)); });
test('helper absence, synchronous CSV false/throw and clipboard Promise rejection never report generated success', async () => { const missing = fixture(); missing.env.FarmaciaDemo.downloadFile = null; assert.equal(missing.controller.refresh().code, 'FOLLOWUP_OUTPUT_HELPER_ERROR'); for (const option of ['failDownload', 'throwDownload']) { const csv = fixture({ helperOptions: { [option]: true } }); assert.equal((await csv.controller.execute('csv')).code, 'FOLLOWUP_OUTPUT_HELPER_ERROR'); assert.notEqual(csv.elements.fhSegOutputStatus.attributes['data-status-code'], 'FOLLOWUP_OUTPUT_GENERATED'); } for (const kind of ['txt', 'excel']) { const value = fixture({ helperOptions: { failClipboard: true } }); assert.equal((await value.controller.execute(kind)).code, 'FOLLOWUP_OUTPUT_HELPER_ERROR'); assert.notEqual(value.elements.fhSegOutputStatus.attributes['data-status-code'], 'FOLLOWUP_OUTPUT_GENERATED'); assert.equal(value.elements.fhSegExportTxt.disabled, true); } });
test('controller is async in-flight safe and marks GENERATED only after clipboard resolution', async () => { const value = fixture({ helperOptions: { deferClipboard: true } }); const first = value.controller.execute('txt'); const second = value.controller.execute('excel'); assert.strictEqual(second, first); assert.equal(value.controller.state().inFlight, true); assert.equal(value.elements.fhSegExportTxt.disabled, true); assert.notEqual(value.elements.fhSegOutputStatus.attributes['data-status-code'], 'FOLLOWUP_OUTPUT_GENERATED'); assert.equal(value.captures.clipboardWrites.length, 1); value.captures.resolveClipboard(); const result = await first; assert.equal(result.code, 'FOLLOWUP_OUTPUT_GENERATED'); await Promise.resolve(); assert.equal(value.controller.state().inFlight, false); assert.equal(value.elements.fhSegExportTxt.disabled, false); assert.equal(value.captures.clipboardWrites.length, 1); });
test('context event invalidates deferred clipboard success and completion keeps the current blocked gate', async () => { let current = context(); const value = fixture({ contextValue: () => current, helperOptions: { deferClipboard: true } }); value.controller.refresh(); const pending = value.controller.execute('txt'); assert.equal(value.controller.state().inFlight, true); current = { ok: false, code: 'LINE_NOT_ACTIVE' }; assert.equal(value.controller.refresh().code, 'FOLLOWUP_OUTPUT_CONTEXT_BLOCKED'); assert.equal(value.elements.fhSegExportTxt.disabled, true); value.captures.resolveClipboard(); const result = await pending; assert.deepEqual(result, { ok: false, code: 'FOLLOWUP_OUTPUT_CONTEXT_BLOCKED' }); await Promise.resolve(); assert.equal(value.controller.state().inFlight, false); assert.equal(value.elements.fhSegOutputStatus.attributes['data-status-code'], 'FOLLOWUP_OUTPUT_CONTEXT_BLOCKED'); assert.equal(value.elements.fhSegExportTxt.disabled, true); assert.deepEqual(Object.values(outputs.AUDIT_IDS).map((id) => value.elements[id].textContent), Array(5).fill('No informado')); });
test('Excel wrong column count fails without false success', async () => { const value = fixture({ helperOptions: { columns: 60 } }); assert.equal((await value.controller.execute('excel')).code, 'FOLLOWUP_OUTPUT_HELPER_ERROR'); });
test('visible state texts and button labels are exact', () => { for (const code of ['FOLLOWUP_OUTPUT_CONTEXT_BLOCKED','FOLLOWUP_OUTPUT_EMPTY','FOLLOWUP_OUTPUT_STORAGE_ERROR','FOLLOWUP_OUTPUT_HELPER_ERROR','FOLLOWUP_OUTPUT_READY','FOLLOWUP_OUTPUT_READY_WITH_UNSAVED_CHANGES','FOLLOWUP_OUTPUT_GENERATED']) assert.ok(outputs.TEXTS[code]); for (const copy of ['Copiar texto JARA (demo)','Descargar CSV canónico','Copiar fila Excel FH']) assert.ok(html.includes(copy)); for (const copy of [outputs.TEXTS.FOLLOWUP_OUTPUT_READY, outputs.TEXTS.FOLLOWUP_OUTPUT_READY_WITH_UNSAVED_CHANGES, outputs.TEXTS.FOLLOWUP_OUTPUT_EMPTY]) assert.ok(outputSource.includes(copy)); });
test('module rereads exact context and confirmed store for every execution without draft or editable DOM clinical reads', () => { assert.match(outputSource, /function execute\(kind\)[\s\S]*resolveProjection\(env/); assert.match(outputSource, /createStore\(env\.sessionStorage\)\.read\(\)/); assert.doesNotMatch(outputSource, /followupDrafts\.v4|getElementById\('fhSegDraft|fhSegPromsExpanded|fhSegDlqiQuestions|fhSeguimientoEa|fhCausalidad|FarmaciaDemo\.findPatient|catalog_snapshot|decisions|movements/); });
test('capture is installed before context and absorbs only three supported targets', () => { const outputPosition = html.indexOf('farmacia_followup_outputs_v4.js'); const contextPosition = html.indexOf('farmacia_followup_context_v4.js'); assert.ok(outputPosition > 0 && outputPosition < contextPosition); assert.match(outputSource, /#fhSegExportTxt, #fhSegExportCsv, #fhSegExcelExportBtn/); assert.match(outputSource, /stopImmediatePropagation/); });
test('context preserves helper identities and defaults to blocked when outputs module is absent', () => { assert.doesNotMatch(contextSource, /function protect\(|__farmaciaFollowupBlockedV4|target\[key\]\s*=/); assert.match(contextSource, /if \(output\) \{ if \(env\.__farmaciaFollowupOutputsV4Installed !== true\) absorb\(event\)/); });
test('legacy source and all substantive NO TOCA scripts remain byte-identical', () => { assert.match(legacySource, /fhSegExportTxt/); for (const file of ['scripts/farmacia_seguimiento.js','scripts/farmacia_followup_drafts_v4.js','scripts/farmacia_followup_persisted_review_v4.js','scripts/farmacia_multitreatment_core.js','scripts/farmacia_excel_row_export.js','scripts/farmacia_first_visit_exports_v4.js']) assert.equal(require('node:child_process').spawnSync('git', ['diff','--quiet','--',file], { cwd: ROOT }).status, 0, file); });
test('excluded legacy clinical concepts are blank in Excel and absent from projection contract', () => { for (const field of ['causalidad_naranjo','causalidad_karch','accion_ea','tipo_movimiento','respuesta_clinica']) assert.equal(outputs.CSV_COLUMNS.includes(field), false); assert.doesNotMatch(outputSource.slice(outputSource.indexOf('var CSV_COLUMNS'), outputSource.indexOf('var TARGETS')), /morisky|causalidad|movimiento|sospechoso|accion/i); });

for (const item of tests) { await item.fn(); passed += 1; console.log(`ok ${passed} - ${item.name}`); }
assert.ok(passed >= 24);
console.log(`farmacia_followup_outputs_v4_check: PASSED_${passed}_CANONICAL_CONFIRMED_VISIT_TXT_CSV_EXCEL_61_GATED_CASES`);
