#!/usr/bin/env node

import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const visits = require(path.join(ROOT, 'scripts/farmacia_followup_confirmed_visit_v4.js'));
const drafts = require(path.join(ROOT, 'scripts/farmacia_followup_drafts_v4.js'));
const html = fs.readFileSync(path.join(ROOT, 'farmacia_seguimiento.html'), 'utf8');
const source = fs.readFileSync(path.join(ROOT, 'scripts/farmacia_followup_confirmed_visit_v4.js'), 'utf8');
let passed = 0;
let cryptoSequence = 0;
const uuidLabels = new Map();
function uuid(label = 'default') { if (!uuidLabels.has(label)) uuidLabels.set(label, uuidLabels.size + 1); return `00000000-0000-4000-8000-${uuidLabels.get(label).toString(16).padStart(12, '0')}`; }
function test(name, fn) { fn(); passed += 1; console.log(`ok ${passed} - ${name}`); }
function draft(patient = 'patient-a', line = 'line-a', savedAt = '2026-07-26T10:00:00.000Z', overrides = {}) {
  return { draft_id: `followup:${line}`, patient_id: patient, line_id: line, kind: 'followup', notes: 'Instantánea sintética',
    mg1: 'si', mg2: 'no', mg3: '', mg4: '', ae_present: 'si', ae_description: 'EA sintético', ae_severity: 'leve', ae_resolution: 'en_seguimiento',
    proms_collected: 'si', dlqi_total: 0, eva_dolor: 4, eva_prurito: 7, saved_at: savedAt, saved_by_demo: 'Profesional FH-01', ...overrides };
}
function draftState(...items) { const state = drafts.emptyState(); for (const item of items) { state.patients[item.patient_id] ||= { lines: {} }; state.patients[item.patient_id].lines[item.line_id] = item; } return state; }
function record(id = 'default', patient = 'patient-a', line = 'line-a', savedAt = '2026-07-26T10:00:00.000Z', confirmedAt = '2026-07-26T11:00:00.000Z', overrides = {}) {
  const recordId = visits.validOpaqueId(id) ? id : uuid(id); const item = draft(patient, line, savedAt); return { record_id: recordId, patient_id: patient, line_id: line, visit_date: '2026-07-26', confirmed_at: confirmedAt,
    confirmed_by_demo: 'Profesional FH-01', source_draft_saved_at: savedAt, source_draft_saved_by_demo: item.saved_by_demo,
    notes: item.notes, mg1: item.mg1, mg2: item.mg2, mg3: item.mg3, mg4: item.mg4, ae_present: item.ae_present,
    ae_description: item.ae_description, ae_severity: item.ae_severity, ae_resolution: item.ae_resolution,
    proms_collected: item.proms_collected, dlqi_total: item.dlqi_total, eva_dolor: item.eva_dolor, eva_prurito: item.eva_prurito, ...overrides };
}
function state(...records) { const value = visits.emptyState(); for (const item of records) value.records[item.record_id] = item; return value; }
function memory(entries = {}, options = {}) { const data = new Map(Object.entries(entries)); const writes = []; let postWrite = false; let injected = false;
  return { data, writes,
    getItem(key) { if (options.failRead) throw new Error('denied'); if (key === visits.STORE_KEY && postWrite && !injected) { injected = true; if (options.postWriteReadFailure) throw new Error('verification denied'); if (options.postWriteMismatch) return 'mismatched verification bytes'; } return data.has(key) ? data.get(key) : null; },
    setItem(key, value) { writes.push(['set', key, String(value)]); if (options.failWrite) throw new Error('denied'); data.set(key, String(value)); if (key === visits.STORE_KEY && (options.postWriteMismatch || options.postWriteReadFailure) && !injected) postWrite = true; },
    removeItem(key) { writes.push(['remove', key]); data.delete(key); }, clear() { throw new Error('forbidden mutation'); } }; }
function element(id) { return { id, value: '', textContent: '', disabled: false, attributes: {}, setAttribute(name, value) { this.attributes[name] = String(value); }, getAttribute(name) { return this.attributes[name] ?? null; } }; }
const UI_IDS = ['currentProfessional', 'fhSegVisitConfirmCard', 'fhSegVisitConfirmStatus', 'fhSegVisitConfirmDate', 'fhSegVisitConfirmProfessional', 'fhSegVisitConfirmButton', ...Object.values(visits.AUDIT_IDS)];
function app({ draftRaw, visitRaw, storage, professional = 'Profesional FH-01', context = null, now = '2026-07-26T12:00:00.000Z' } = {}) {
  const backing = storage || memory({ ...(draftRaw === undefined ? {} : { [drafts.STORE_KEY]: draftRaw }), ...(visitRaw === undefined ? {} : { [visits.STORE_KEY]: visitRaw }) });
  const elements = Object.fromEntries(UI_IDS.map((id) => [id, element(id)])); elements.currentProfessional.textContent = professional;
  const events = [];
  const env = { sessionStorage: backing, FarmaciaFollowupDraftsV4: drafts, crypto: { randomUUID: () => `10000000-0000-4000-8000-${(++cryptoSequence).toString(16).padStart(12, '0')}` },
    CustomEvent: class { constructor(type, options) { this.type = type; this.detail = options.detail; } },
    document: { getElementById: (id) => elements[id] || null, dispatchEvent(event) { events.push(event); return true; } }, __farmaciaFollowupContextV4: context || { ok: true, code: 'CANONICAL_ACTIVE_CONTEXT_READY', patient_id: 'patient-a', line_id: 'line-a', line: { status: 'active' } } };
  const controller = visits.createController(env, { storage: backing, crypto: env.crypto, now: () => now });
  const detail = (overrides = {}) => ({ patient_id: 'patient-a', line_id: 'line-a', ready: true, dirty: false, storage_error: '', has_saved: true, reason: 'TEST', ...overrides });
  return { backing, elements, env, controller, detail, events };
}

test('store key schema and root are exact with a prototype-free record map', () => { const empty = visits.emptyState(); assert.equal(visits.STORE_KEY, 'farmaciaDemo.followupConfirmedVisits.v1'); assert.equal(empty.schema, visits.STORE_KEY); assert.deepEqual(Object.keys(empty.records), []); assert.equal(Object.getPrototypeOf(empty.records), null); });
test('record contract has exactly 21 fields', () => { assert.equal(visits.RECORD_FIELDS.length, 21); assert.deepEqual(Object.keys(record()).sort(), visits.RECORD_FIELDS.slice().sort()); });
test('valid exact record and root pass', () => assert.equal(visits.validateState(state(record())).ok, true));
test('corrupt JSON incompatible schema and storage unavailable fail closed', () => { for (const backing of [memory({ [visits.STORE_KEY]: '{' }), memory({ [visits.STORE_KEY]: JSON.stringify({ schema: 'wrong', records: {} }) }), memory({}, { failRead: true })]) assert.equal(visits.createStore(backing).read().ok, false); });
test('root and record extras fail closed', () => { assert.equal(visits.validateState({ ...state(record()), extra: true }).ok, false); assert.equal(visits.validateState(state(record('x', undefined, undefined, undefined, undefined, { extra: true }))).ok, false); });
test('invalid scalar types dates timestamps enums and numeric bounds fail closed', () => { for (const patch of [{ notes: null }, { visit_date: '' }, { visit_date: '2026-02-30' }, { confirmed_at: 'today' }, { mg1: 'quizá' }, { dlqi_total: 31 }, { eva_dolor: '0' }]) assert.equal(visits.validateState(state(record('x', undefined, undefined, undefined, undefined, patch))).ok, false); });
test('record map key must equal opaque record_id', () => { const value = state(); value.records[uuid('foreign-key')] = record('actual'); assert.equal(visits.validateState(value).ok, false); });
test('duplicate patient line source timestamp is invalid', () => assert.equal(visits.validateState(state(record('a'), record('b', 'patient-a', 'line-a', undefined, '2026-07-26T12:00:00.000Z'))).ok, false));
test('equal confirmed_at in one partition is an invalid ambiguous store', () => assert.equal(visits.validateState(state(record('tie-a', 'patient-a', 'line-a', 'saved-a'), record('tie-b', 'patient-a', 'line-a', 'saved-b'))).ok, false));
test('equal confirmed_at across different partitions remains unambiguous', () => assert.equal(visits.validateState(state(record('partition-a', 'patient-a', 'line-a'), record('partition-b', 'patient-b', 'line-b'))).ok, true));
test('append preserves prior record bytes semantically and only adds', () => { const backing = memory({ [visits.STORE_KEY]: JSON.stringify(state(record('old'))) }); const result = visits.createStore(backing).append(record('new', 'patient-a', 'line-a', '2026-07-26T13:00:00.000Z', '2026-07-26T14:00:00.000Z')); assert.equal(result.ok, true); const stored = JSON.parse(backing.data.get(visits.STORE_KEY)); assert.deepEqual(stored.records[uuid('old')], record('old')); assert.equal(Object.keys(stored.records).length, 2); });
test('repeat source is rejected without write', () => { const backing = memory({ [visits.STORE_KEY]: JSON.stringify(state(record())) }); const before = backing.data.get(visits.STORE_KEY); assert.equal(visits.createStore(backing).append(record('other')).code, 'VISIT_CONFIRM_ALREADY_CONFIRMED'); assert.equal(backing.data.get(visits.STORE_KEY), before); assert.deepEqual(backing.writes, []); });
test('write failure preserves previous bytes', () => { const raw = JSON.stringify(state(record())); const backing = memory({ [visits.STORE_KEY]: raw }, { failWrite: true }); assert.equal(visits.createStore(backing).append(record('new', 'patient-a', 'line-a', 'later')).ok, false); assert.equal(backing.data.get(visits.STORE_KEY), raw); });
test('post-write mismatch rolls back and verifies exact prior bytes', () => { const raw = JSON.stringify(state(record('prior'))); const backing = memory({ [visits.STORE_KEY]: raw }, { postWriteMismatch: true }); const result = visits.createStore(backing).append(record('candidate', 'patient-a', 'line-a', 'later', '2026-07-26T12:00:00.000Z')); assert.deepEqual([result.ok, result.restored], [false, true]); assert.equal(backing.data.get(visits.STORE_KEY), raw); });
test('post-write verification read failure rolls back prior absence', () => { const backing = memory({}, { postWriteReadFailure: true }); const result = visits.createStore(backing).append(record('candidate-absent')); assert.deepEqual([result.ok, result.restored], [false, true]); assert.equal(backing.data.has(visits.STORE_KEY), false); assert.ok(backing.writes.some((entry) => entry[0] === 'remove' && entry[1] === visits.STORE_KEY)); });
test('append refuses to write without rollback capabilities', () => { const backing = memory(); backing.removeItem = undefined; assert.equal(visits.createStore(backing).append(record('no-capability')).ok, false); assert.deepEqual(backing.writes, []); });
test('append rejects a confirmed_at partition tie without any write', () => { const raw = JSON.stringify(state(record('tie-prior'))); const backing = memory({ [visits.STORE_KEY]: raw }); const result = visits.createStore(backing).append(record('tie-next', 'patient-a', 'line-a', 'new-source')); assert.equal(result.code, 'VISIT_CONFIRM_STORAGE_ERROR'); assert.equal(backing.data.get(visits.STORE_KEY), raw); assert.deepEqual(backing.writes, []); });
test('source directly rereads only exact v4 draft partition and validates it', () => { const raw = JSON.stringify(draftState(draft('patient-a', 'line-a'), draft('patient-a', 'line-b', undefined, { notes: 'foreign' }))); const backing = memory({ [drafts.STORE_KEY]: raw }); const found = visits.readDraft({ sessionStorage: backing, FarmaciaFollowupDraftsV4: drafts }, 'patient-a', 'line-a'); assert.equal(found.draft.notes, 'Instantánea sintética'); assert.equal(backing.writes.length, 0); });
test('corrupt extra and incompatible draft sources fail closed', () => { for (const raw of ['{', JSON.stringify({ ...draftState(draft()), extra: true }), JSON.stringify({ schema: 'v3', patients: {} })]) assert.equal(visits.readDraft({ sessionStorage: memory({ [drafts.STORE_KEY]: raw }), FarmaciaFollowupDraftsV4: drafts }, 'patient-a', 'line-a').ok, false); });
test('latest audit is selected by confirmed_at in exact partition', () => { const records = state(record('global', 'patient-b', 'line-b', 'x', '2026-07-26T20:00:00.000Z'), record('old', 'patient-a', 'line-a', 'a', '2026-07-26T10:00:00.000Z'), record('latest', 'patient-a', 'line-a', 'b', '2026-07-26T11:00:00.000Z')).records; assert.equal(visits.latestFor(records, 'patient-a', 'line-a').record_id, uuid('latest')); });
test('opaque IDs require canonical cryptographic UUID v4 and no Math.random', () => { const valid = '123e4567-e89b-42d3-a456-426614174000'; assert.equal(visits.opaqueId({ randomUUID: () => valid }), valid); for (const poison of ['opaque', '__proto__', 'constructor', 'prototype', '123E4567-E89B-42D3-A456-426614174000', '123e4567-e89b-12d3-a456-426614174000']) { assert.equal(visits.validOpaqueId(poison), false); assert.equal(visits.opaqueId({ randomUUID: () => poison }), ''); } assert.equal(visits.opaqueId(null), ''); assert.doesNotMatch(source, /Math\.random/); });
test('poison and arbitrary record keys fail closed without prototype effects', () => { for (const poison of ['__proto__', 'constructor', 'prototype', 'arbitrary']) { const parsed = JSON.parse(`{"schema":"${visits.SCHEMA}","records":{"${poison}":${JSON.stringify(record('poison-record', undefined, undefined, undefined, undefined, { record_id: poison }))}}}`); assert.equal(visits.validateState(parsed).ok, false); } const safe = visits.emptyState().records; safe.__proto__ = record('safe-proto'); assert.equal(Object.keys(safe).includes('__proto__'), true); assert.equal(Object.getPrototypeOf(safe), null); });
test('incoherent historical unknown mismatch and storage-event errors block', () => { const item = app({ draftRaw: JSON.stringify(draftState(draft())) }); for (const detail of [item.detail({ ready: false }), item.detail({ storage_error: 'DRAFT_STORAGE_UNAVAILABLE' }), item.detail({ line_id: 'foreign' })]) assert.notEqual(item.controller.applyDraftState(detail).code, 'VISIT_CONFIRM_READY'); });
test('empty, dirty and ready states use exact status codes and text', () => { const empty = app(); assert.equal(empty.controller.applyDraftState(empty.detail()).code, 'VISIT_CONFIRM_EMPTY'); const ready = app({ draftRaw: JSON.stringify(draftState(draft())) }); assert.equal(ready.controller.applyDraftState(ready.detail({ dirty: true })).code, 'VISIT_CONFIRM_UNSAVED_CHANGES'); assert.equal(ready.elements.fhSegVisitConfirmStatus.textContent, visits.DIRTY_TEXT); assert.equal(ready.controller.applyDraftState(ready.detail()).code, 'VISIT_CONFIRM_READY'); assert.equal(ready.elements.fhSegVisitConfirmStatus.textContent, visits.READY_TEXT); });
test('date and visible professional are explicit confirmation gates', () => { const item = app({ draftRaw: JSON.stringify(draftState(draft())) }); item.controller.applyDraftState(item.detail()); assert.equal(item.controller.confirm().code, 'VISIT_CONFIRM_DATE_REQUIRED'); item.elements.fhSegVisitConfirmDate.value = '2026-07-26'; item.elements.currentProfessional.textContent = ''; assert.equal(item.controller.confirm().code, 'VISIT_CONFIRM_PROFESSIONAL_REQUIRED'); });
test('confirmation copies the exact persisted snapshot and leaves draft bytes untouched', () => { const sourceDraft = draft(); const raw = JSON.stringify(draftState(sourceDraft)); const item = app({ draftRaw: raw }); item.controller.applyDraftState(item.detail()); item.elements.fhSegVisitConfirmDate.value = '2026-07-27'; const result = item.controller.confirm(); assert.equal(result.code, 'VISIT_CONFIRMED'); assert.equal(item.backing.data.get(drafts.STORE_KEY), raw); assert.deepEqual(Object.fromEntries(visits.COPY_FIELDS.map((field) => [field, result.record[field]])), Object.fromEntries(visits.COPY_FIELDS.map((field) => [field, sourceDraft[field]]))); assert.equal(item.elements.fhSegVisitConfirmStatus.textContent, visits.CONFIRMED_TEXT); });
test('successful append emits one minimal exact confirmed-visit event', () => { const item = app({ draftRaw: JSON.stringify(draftState(draft())) }); item.controller.applyDraftState(item.detail()); item.elements.fhSegVisitConfirmDate.value = '2026-07-26'; const result = item.controller.confirm(); assert.equal(item.events.length, 1); assert.equal(item.events[0].type, 'farmacia:followup-confirmed-visit-v1'); assert.deepEqual(item.events[0].detail, { patient_id: result.record.patient_id, line_id: result.record.line_id, record_id: result.record.record_id, confirmed_at: result.record.confirmed_at }); assert.deepEqual(Object.keys(item.events[0].detail), ['patient_id', 'line_id', 'record_id', 'confirmed_at']); });
test('poisoned editable DOM and legacy variables cannot alter snapshot', () => { const item = app({ draftRaw: JSON.stringify(draftState(draft())) }); item.env.fhSegDraftNotes = { value: 'poison' }; item.controller.applyDraftState(item.detail()); item.elements.fhSegVisitConfirmDate.value = '2026-07-26'; assert.equal(item.controller.confirm().record.notes, 'Instantánea sintética'); });
test('double confirmation and reload report already confirmed with no duplicate', () => { const item = app({ draftRaw: JSON.stringify(draftState(draft())) }); item.controller.applyDraftState(item.detail()); item.elements.fhSegVisitConfirmDate.value = '2026-07-26'; assert.equal(item.controller.confirm().ok, true); assert.equal(item.controller.confirm().code, 'VISIT_CONFIRMED'); const reloaded = app({ storage: item.backing }); assert.equal(reloaded.controller.applyDraftState(reloaded.detail()).code, 'VISIT_CONFIRM_ALREADY_CONFIRMED'); assert.equal(Object.keys(JSON.parse(item.backing.data.get(visits.STORE_KEY)).records).length, 1); });
test('new saved_at and a later confirmation time permit another immutable visit', () => { const backing = memory({ [drafts.STORE_KEY]: JSON.stringify(draftState(draft())) }); const first = app({ storage: backing }); first.controller.applyDraftState(first.detail()); first.elements.fhSegVisitConfirmDate.value = '2026-07-26'; first.controller.confirm(); backing.data.set(drafts.STORE_KEY, JSON.stringify(draftState(draft('patient-a', 'line-a', '2026-07-27T10:00:00.000Z')))); const second = app({ storage: backing, now: '2026-07-26T13:00:00.000Z' }); second.controller.applyDraftState(second.detail()); second.elements.fhSegVisitConfirmDate.value = '2026-07-27'; assert.equal(second.controller.confirm().ok, true); assert.equal(Object.keys(JSON.parse(backing.data.get(visits.STORE_KEY)).records).length, 2); });
test('controller tie prevention cannot show success or diverge after reload', () => { const raw = JSON.stringify(state(record('controller-prior', 'patient-a', 'line-a', 'old-source', '2026-07-26T12:00:00.000Z'))); const item = app({ draftRaw: JSON.stringify(draftState(draft('patient-a', 'line-a', 'new-source'))), visitRaw: raw }); item.controller.applyDraftState(item.detail()); item.elements.fhSegVisitConfirmDate.value = '2026-07-26'; const result = item.controller.confirm(); assert.equal(result.code, 'VISIT_CONFIRM_STORAGE_ERROR'); assert.equal(item.elements.fhSegVisitConfirmStatus.attributes['data-status-code'], 'VISIT_CONFIRM_STORAGE_ERROR'); assert.equal(item.backing.data.get(visits.STORE_KEY), raw); const reloaded = app({ storage: item.backing }); assert.notEqual(reloaded.controller.applyDraftState(reloaded.detail()).code, 'VISIT_CONFIRMED'); assert.equal(reloaded.elements.fhSegVisitConfirmRecordId.textContent, uuid('controller-prior')); });
test('partition change clears foreign audit and date', () => { const backing = memory({ [drafts.STORE_KEY]: JSON.stringify(draftState(draft('patient-a', 'line-a'), draft('patient-a', 'line-b'))), [visits.STORE_KEY]: JSON.stringify(state(record())) }); const item = app({ storage: backing }); item.controller.applyDraftState(item.detail()); item.elements.fhSegVisitConfirmDate.value = '2026-07-26'; item.env.__farmaciaFollowupContextV4 = { ok: true, code: 'CANONICAL_ACTIVE_CONTEXT_READY', patient_id: 'patient-a', line_id: 'line-b', line: { status: 'active' } }; item.controller.applyDraftState(item.detail({ line_id: 'line-b' })); assert.equal(item.elements.fhSegVisitConfirmRecordId.textContent, 'No informado'); assert.equal(item.elements.fhSegVisitConfirmDate.value, ''); });
test('module mutates only its own confirmed store rollback and no draft/legacy data', () => { assert.match(source, /removeItem\(STORE_KEY\)/); assert.equal((source.match(/removeItem\(/g) || []).length, 1); assert.doesNotMatch(source, /\.clear\s*\(|followupDrafts\.v[123]|multitreatment\.v1|migrat|innerHTML|CSV|Excel|JARA|causalidad|recomendaci[oó]n|suspected/i); });
test('HTML card order, exact visible copy and script order are contractual', () => { const review = html.indexOf('fhSegPersistedReviewCard'); const card = html.indexOf('fhSegVisitConfirmCard'); const draftCard = html.indexOf('fhSegDraftCard'); assert.ok(review < card && card < draftCard); for (const text of ['Confirmar visita de seguimiento (demo)', 'Visita confirmada de demo. No constituye firma clínica, integración JARA ni registro productivo.', ...Object.values(visits.AUDIT_IDS)]) assert.ok(html.includes(text)); const scripts = ['farmacia_followup_drafts_v4.js', 'farmacia_followup_persisted_review_v4.js', 'farmacia_followup_confirmed_visit_v4.js', 'farmacia_followup_context_v4.js'].map((name) => html.indexOf(name)); assert.deepEqual(scripts, scripts.slice().sort((a, b) => a - b)); });
assert.ok(passed >= 33);
console.log(`farmacia_followup_confirmed_visit_v4_check: PASSED_${passed}_STRICT_IMMUTABLE_EXACT_PARTITION_CONFIRMATION_CASES`);
